### PR TITLE
Please merge my latest changes into your branch and take it from there.

### PR DESCRIPTION
**Pull request by bravemaster3**
Changed files:
-execve.c: added freeing buffer on receiving CTRL+D signal, and free buffer only outside the loop! Important
-execve1.c: addresses a single child process, as we will do for our simple shell. 
If you want to compare the new files with the previous version (executable ./exec), use valgrind, and 
Try pressing ENTER without any command a few times, and some wrong commands... then, press CTRL+D. You will notice some memory leak, or some extra frees.
This is solved by my changes.

VERY IMPORTANT, 
Adding a check for when only a new line is gotten in the buffer (that is pressing only enter without any command) is important, because then, you should do nothing but start the loop again. I added this with 
if (n_char == 1 && *buffer == '\n')
	continue;
By adding this, our prompt now acts normally, and also alongside the above mentioned changes, no error and no memory leaks, even when you type a wrong command, or enter no command.

THE CURRENT execve1 can be our starting building block. If you try to simplify anything, make sure to check all these conditions

After compilation,
valgrind -s --leak-check=full --show-leak-kinds=all --track-origins=yes --tool=memcheck ./<exec_name>

try pressing ENTER a few times, 
try entering some nonsense commands, 
Try entering some real commands like /bin/ls

THen, CTRL+D

If there is any error at all, then it was not well done.

### CODE REVIEW

**Comment by Paphra** [comment]
Thanks so much for this detailed and comprehensive update

**Comment by Paphra** [comment]
I have noticed some memory leak after some tests, with ```execve1.c```

**Comment by bravemaster3** [comment]
I am really surprised. There was no leak when I tested.
What did you test to find that leak?
New line? 
Unfound commands? 
Commands that are found in the path?
Something else?

**Comment by Paphra** [comment]
nothing much, I just ran it and exited

**Pull request merged**
